from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from .building_blocks import BBSelectionMode, BBScoreMode, BBWeightMode
from .bb_search import BBSearchMode

ProblemType = Literal["classification", "regression"]
StopCriterion = Literal["gen", "time", "eval"]
ArtifactLayout = Literal["both", "nested", "root"]
LREncoding = Literal["binary", "spin"]


@dataclass(frozen=True)
class GAConfig:
    """Configuration for one GA/BLuR-GA optimization run.

    ga_type:
        0 = standard GA, 1 = empirical linkage GA, 
        2 = pairwise Lasso, 3 = linkage-guided pair-only CGGA-style GA,
        4 = linkage-guided pair + Fisher-main CGGA-style GA.
    classifier_type:
        1 = KNN with k=3, 2 = KNN with k=5.
    crossover_probability:
        Probability used by the standard GA.
    ll_crossover_ratio:
        Fraction of offspring positions generated by crossover before the empirical-linkage variant's
        empirical linkage mutation is used. This intentionally separates the
        two meanings that were overloaded as p_cross in the C/Python port.

    Linkage graph logging:
        save_linkage_events stores one row for every pair tested by mutation
        with linkage learning. save_graph_snapshots stores the cumulative edge
        list after selected generations so the graph can be replayed as an
        animation. snapshot interval 1 means every generation.
    """

    classifier_type: int = 1
    ga_type: int = 1
    popsize: int = 100
    crossover_probability: float = 0.4
    ll_crossover_ratio: float = 0.4
    mutation_probability: float | None = None
    tournament_size: int = 3
    tau_reset: int = 50
    resetpop_rate: float = 0.99
    local_search: bool = False
    stop: StopCriterion = "gen"
    max_gen: int = 200
    max_time: float | None = None
    max_evals: int | None = None
    edge_epsilon: float = 1e-6
    save_generation_trace: bool = False
    save_linkage_events: bool = False
    save_graph_snapshots: bool = False
    save_evig_edge_files: bool = False
    graph_snapshot_interval: int = 1
    graph_snapshot_top_k: int | None = None
    graph_snapshot_min_weight: float = 0.0
    fitness_weight_score: float = 0.98
    fitness_weight_sparsity: float = 0.02
    cache_fitness: bool = True

    # Regression-linkage learner settings for ga_type 2/3/4.
    # ga_type 2: theory-aligned pairwise Lasso using binary active-pair terms.
    # ga_type 3: CGGA-style guided crossover/mutation using learned pairwise linkage only.
    # ga_type 4: CGGA-style guided crossover/mutation using learned pairwise linkage plus Fisher main effects.
    lr_gap_gen: int = 5
    lr_min_samples: int = 20
    lr_sparse_alpha: float = 0.001
    # Theory-guided PSLE/MPSLE settings for ga_type 2/3.
    # If enabled, lambda_g is computed at each regression fit as
    # c_lambda * sigma_hat_g * sqrt(2 log(2 p_g / delta) / n_g).
    # If enabled, the minimum archive size is at least
    # ceil(c_n * s_hat * log(2 p_g / delta)).
    lr_auto_alpha: bool = True
    lr_alpha_c: float = 1.0
    lr_delta: float = 0.05
    lr_auto_min_samples: bool = True
    lr_expected_edges: int | None = None
    lr_refit_expected_edges: int | None = None
    lr_min_samples_c: float = 1.0
    lr_stability_subsamples: int = 0
    lr_stability_fraction: float = 0.75
    lr_edge_min_weight: float = 0.0
    lr_edge_top_k: int | None = None
    # binary: pair term x_i*x_j, positive edge = co-selection effect.
    # spin: pair term u_i*u_j where u=2x-1, positive edge = same-state effect.
    lr_encoding: LREncoding = "binary"
    # matrix_free is kept as a backward-compatible alias for the exact dual_ridge solver.
    lr_solver: Literal["auto", "sklearn_full", "dual_ridge", "matrix_free"] = "auto"
    lr_matrix_free_threshold: int = 700
    lr_matrix_free_max_iter: int = 32
    lr_matrix_free_tol: float = 1e-4
    lr_matrix_free_step_scale: float = 0.5
    lr_matrix_free_dtype: Literal["float64", "float32"] = "float32"

    # CGGA-style guided operator settings for ga_type 3/4.
    # These are analogous to k1/k2 in Zhou & Hua (2022), but score candidates
    # with the learned linkage graph/building blocks rather than data correlation.
    guided_crossover_checks: int = 40
    guided_mutation_checks: int = 40
    guided_pair_weight: float = 1.0
    guided_main_weight: float = 1.0
    guided_sparsity_weight: float = 0.02

    # Optional LTGA-style building-block extraction from the current linkage graph.
    # When bb_search_mode is "none", blocks are diagnostic only.  The two active
    # search modes are "uniform" and "pattern_refine" for ga_type 2/3.
    build_building_blocks: bool = False
    bb_weight_mode: BBWeightMode = "absolute"
    bb_score_mode: Literal["current", "current_stability", "current_stability_regression"] = "current_stability_regression"
    bb_selection_mode: BBSelectionMode = "coverage_budget"
    bb_search_mode: BBSearchMode = "none"
    bb_gawll_update_interval: int | None = None
    bb_min_block_size: int = 2
    bb_max_block_size: int | None = None
    bb_max_blocks: int = 20
    bb_max_blocks_cap: int = 128
    bb_coverage_ratio: float = 0.50
    bb_coverage_min: int = 10
    bb_coverage_cap: int = 256
    bb_snapshot_interval: int = 1
    bb_external_penalty: float = 0.25
    bb_size_penalty: float = 0.01
    bb_pattern_top_fraction: float = 0.30
    bb_pattern_min_support: int = 2
    bb_refine_fraction: float = 0.20
    bb_max_refine_trials: int | None = 10
    bb_accept_equal_sparser: bool = True
    bb_shuffle_blocks: bool = True
    bb_signed_repair_probability: float = 0.75

    # Optional exploration boost before the first regression-linkage fit.
    # This keeps early generations more diverse while lr_expected_edges/auto
    # min-samples has not yet allowed the first LR graph to be learned. Once
    # the first LR fit succeeds, the optimizer automatically returns to the
    # normal mutation and replacement behavior.
    pre_lr_explore: bool = False
    pre_lr_mutation_multiplier: float = 3.0
    pre_lr_immigrant_rate: float = 0.0

    def __post_init__(self) -> None:
        if self.classifier_type not in (1, 2):
            raise ValueError("classifier_type must be 1 (KNN-3) or 2 (KNN-5).")
        if self.ga_type not in (0, 1, 2, 3, 4):
            raise ValueError("ga_type must be 0 standard, 1 empirical linkage GA, 2 pairwise Lasso, 3 linkage-guided pair, or 4 linkage-guided pair+Fisher.")
        if self.popsize < 4:
            raise ValueError("popsize must be at least 4.")
        if not 0.0 <= self.crossover_probability <= 1.0:
            raise ValueError("crossover_probability must be in [0, 1].")
        if not 0.0 <= self.ll_crossover_ratio <= 1.0:
            raise ValueError("ll_crossover_ratio must be in [0, 1].")
        if self.tournament_size < 1:
            raise ValueError("tournament_size must be positive.")
        if self.max_gen < 1:
            raise ValueError("max_gen must be positive.")
        if self.edge_epsilon < 0:
            raise ValueError("edge_epsilon must be non-negative.")
        if self.graph_snapshot_interval < 1:
            raise ValueError("graph_snapshot_interval must be at least 1.")
        if self.graph_snapshot_top_k is not None and self.graph_snapshot_top_k < 1:
            raise ValueError("graph_snapshot_top_k must be positive or None.")
        if self.graph_snapshot_min_weight < 0:
            raise ValueError("graph_snapshot_min_weight must be non-negative.")
        if self.lr_gap_gen < 1:
            raise ValueError("lr_gap_gen must be at least 1.")
        if self.lr_min_samples < 2:
            raise ValueError("lr_min_samples must be at least 2.")
        if self.lr_sparse_alpha < 0:
            raise ValueError("lr_sparse_alpha must be non-negative.")
        if self.lr_alpha_c < 0:
            raise ValueError("lr_alpha_c must be non-negative.")
        if not 0.0 < self.lr_delta < 1.0:
            raise ValueError("lr_delta must be in (0, 1).")
        if self.lr_expected_edges is not None and self.lr_expected_edges < 1:
            raise ValueError("lr_expected_edges must be positive or None.")
        if self.lr_refit_expected_edges is not None and self.lr_refit_expected_edges < 1:
            raise ValueError("lr_refit_expected_edges must be positive or None.")
        if self.lr_min_samples_c <= 0:
            raise ValueError("lr_min_samples_c must be positive.")
        if self.lr_stability_subsamples < 0:
            raise ValueError("lr_stability_subsamples must be non-negative.")
        if not 0.0 < self.lr_stability_fraction <= 1.0:
            raise ValueError("lr_stability_fraction must be in (0, 1].")
        if self.lr_edge_min_weight < 0:
            raise ValueError("lr_edge_min_weight must be non-negative.")
        if self.lr_edge_top_k is not None and self.lr_edge_top_k < 1:
            raise ValueError("lr_edge_top_k must be positive or None.")
        if self.lr_encoding not in {"binary", "spin"}:
            raise ValueError("lr_encoding must be one of: binary, spin.")
        if self.lr_solver not in {"auto", "sklearn_full", "dual_ridge", "matrix_free"}:
            raise ValueError("lr_solver must be one of: auto, sklearn_full, dual_ridge, matrix_free.")
        if self.lr_matrix_free_threshold < 1:
            raise ValueError("lr_matrix_free_threshold must be at least 1.")
        if self.lr_matrix_free_max_iter < 1:
            raise ValueError("lr_matrix_free_max_iter must be at least 1.")
        if self.lr_matrix_free_tol < 0:
            raise ValueError("lr_matrix_free_tol must be non-negative.")
        if self.lr_matrix_free_step_scale <= 0:
            raise ValueError("lr_matrix_free_step_scale must be positive.")
        if self.lr_matrix_free_dtype not in {"float64", "float32"}:
            raise ValueError("lr_matrix_free_dtype must be float64 or float32.")
        if self.guided_crossover_checks < 0:
            raise ValueError("guided_crossover_checks must be non-negative.")
        if self.guided_mutation_checks < 0:
            raise ValueError("guided_mutation_checks must be non-negative.")
        if self.guided_pair_weight < 0:
            raise ValueError("guided_pair_weight must be non-negative.")
        if self.guided_main_weight < 0:
            raise ValueError("guided_main_weight must be non-negative.")
        if self.guided_sparsity_weight < 0:
            raise ValueError("guided_sparsity_weight must be non-negative.")
        if self.bb_weight_mode not in {"absolute", "signed", "positive"}:
            raise ValueError("bb_weight_mode must be one of: absolute, signed, positive.")
        if self.bb_score_mode not in {"current", "current_stability", "current_stability_regression"}:
            raise ValueError("bb_score_mode must be one of: current, current_stability, current_stability_regression.")
        if self.bb_selection_mode not in {"count", "coverage_budget"}:
            raise ValueError("bb_selection_mode must be one of: count, coverage_budget.")
        if self.bb_search_mode not in {"none", "uniform", "pattern_refine"}:
            raise ValueError("bb_search_mode must be one of: none, uniform, pattern_refine.")
        if self.bb_search_mode != "none" and self.ga_type not in (1, 2, 3, 4):
            raise ValueError("bb_search_mode requires a linkage-capable ga_type: 1, 2, 3, or 4.")
        if self.bb_gawll_update_interval is not None and self.bb_gawll_update_interval < 1:
            raise ValueError("bb_gawll_update_interval must be None or at least 1.")
        if self.bb_min_block_size < 2:
            raise ValueError("bb_min_block_size must be at least 2.")
        if self.bb_max_block_size is not None and self.bb_max_block_size < self.bb_min_block_size:
            raise ValueError("bb_max_block_size must be None or >= bb_min_block_size.")
        if self.bb_max_blocks < 1:
            raise ValueError("bb_max_blocks must be positive.")
        if self.bb_max_blocks_cap < 1:
            raise ValueError("bb_max_blocks_cap must be positive.")
        if not 0.0 < self.bb_coverage_ratio <= 1.0:
            raise ValueError("bb_coverage_ratio must be in (0, 1].")
        if self.bb_coverage_min < self.bb_min_block_size:
            raise ValueError("bb_coverage_min must be >= bb_min_block_size.")
        if self.bb_coverage_cap < self.bb_coverage_min:
            raise ValueError("bb_coverage_cap must be >= bb_coverage_min.")
        if self.bb_snapshot_interval < 1:
            raise ValueError("bb_snapshot_interval must be at least 1.")
        if self.bb_external_penalty < 0:
            raise ValueError("bb_external_penalty must be non-negative.")
        if self.bb_size_penalty < 0:
            raise ValueError("bb_size_penalty must be non-negative.")
        if not 0.0 < self.bb_pattern_top_fraction <= 1.0:
            raise ValueError("bb_pattern_top_fraction must be in (0, 1].")
        if self.bb_pattern_min_support < 1:
            raise ValueError("bb_pattern_min_support must be at least 1.")
        if not 0.0 < self.bb_refine_fraction <= 1.0:
            raise ValueError("bb_refine_fraction must be in (0, 1].")
        if self.bb_max_refine_trials is not None and self.bb_max_refine_trials < 1:
            raise ValueError("bb_max_refine_trials must be None or positive.")
        if not 0.0 <= self.bb_signed_repair_probability <= 1.0:
            raise ValueError("bb_signed_repair_probability must be in [0, 1].")
        if self.pre_lr_mutation_multiplier < 1.0:
            raise ValueError("pre_lr_mutation_multiplier must be at least 1.0.")
        if not 0.0 <= self.pre_lr_immigrant_rate <= 1.0:
            raise ValueError("pre_lr_immigrant_rate must be in [0, 1].")

    @property
    def _regression_stage_for_validation(self) -> str | None:
        return {2: "pairwise_lasso", 3: "pairwise_lasso", 4: "pairwise_lasso"}.get(self.ga_type)

    @property
    def knn_k(self) -> int:
        return 3 if self.classifier_type == 1 else 5


@dataclass(frozen=True)
class ExperimentConfig:
    """Configuration for nested CV experiments."""

    outer_folds: int = 3
    inner_folds: int = 3
    repeats: int = 1
    seed: int = 1
    shuffle: bool = True
    output_dir: Path = Path("results_nested")
    run_prefix: str = ""
    artifact_layout: ArtifactLayout = "both"
    write_aggregate_outputs: bool = True

    def __post_init__(self) -> None:
        if self.outer_folds < 2:
            raise ValueError("outer_folds must be at least 2.")
        if self.inner_folds < 2:
            raise ValueError("inner_folds must be at least 2.")
        if self.repeats < 1:
            raise ValueError("repeats must be positive.")
        if self.artifact_layout not in {"both", "nested", "root"}:
            raise ValueError("artifact_layout must be one of: both, nested, root.")
