#!/bin/bash
set -euo pipefail

# Submit one SLURM array per (dataset, classifier, ga_type, outer fold), using
# prepared_tabarena/manifest.csv generated by scripts/prepare_existing_tabarena.py.
# Run from the project root after preparing data locally or on the shared FS.

MANIFEST="${MANIFEST:-../Dataset/prepared_tabarena/manifest.csv}"
DATA_DIR="${DATA_DIR:-../Dataset/prepared_tabarena}"
OUT_ROOT="${OUT_ROOT:-/nfs/scratch/<user>/blur_ga_tabarena_results}"
RUNS="${RUNS:-10}"
OUTER_FOLDS="${OUTER_FOLDS:-3}"
INNER_FOLDS="${INNER_FOLDS:-3}"
MAX_GEN="${MAX_GEN:-200}"
POPSIZE="${POPSIZE:-100}"
CLASSIFIERS=(${CLASSIFIERS:-1})
GA_TYPES=(${GA_TYPES:-0 1 2 3 4 5 6 7})

method_folder_name() {
  case "$1" in
    0) echo "standard_ga" ;;
    1) echo "empirical_linkage_legacy" ;;
    2) echo "blur_ga_stage1_pairwise" ;;
    3) echo "blur_ga_stage2_main_pairwise" ;;
    4) echo "blur_ga_stage3_sparse" ;;
    5) echo "blur_ga_stage4_sparse_excess" ;;
    6) echo "blur_ga_pairwise_lasso" ;;
    7) echo "blur_ga_main_pairwise_lasso" ;;
    *) echo "method_$1" ;;
  esac
}


if [[ ! -f "$MANIFEST" ]]; then
  echo "Manifest not found: $MANIFEST" >&2
  echo "Create it first, e.g.:" >&2
  echo "  python scripts/prepare_existing_tabarena.py --source-dir openml_tabarena_processed --output-dir prepared_tabarena --max-samples 10000 --min-features 10 --overwrite" >&2
  exit 1
fi

mkdir -p "$OUT_ROOT"
mapfile -t DATASETS < <(python - <<'PY' "$MANIFEST"
import pandas as pd, sys
m = pd.read_csv(sys.argv[1])
for key in m['dataset_key'].astype(str):
    print(key)
PY
)

echo "Datasets from manifest: ${#DATASETS[@]}"
for dataset in "${DATASETS[@]}"; do
  for classifier in "${CLASSIFIERS[@]}"; do
    for ga_type in "${GA_TYPES[@]}"; do
      for ((fold=0; fold<OUTER_FOLDS; fold++)); do
        jobname="BLuR-GA_${dataset}_c${classifier}_a${ga_type}_f${fold}"
        echo "Submitting dataset=${dataset}, classifier=${classifier}, ga_type=${ga_type}, outer_fold=${fold}, repeats=0..$((RUNS-1))"
        sbatch \
          --job-name="$jobname" \
          --array=0-$((RUNS-1)) \
          hpc/job_slurm_blur_ga_nested_fold.sh \
          "$dataset" "$classifier" "$ga_type" "$fold" "$OUT_ROOT/${dataset}/$(method_folder_name "$ga_type")" \
          --data-dir "$DATA_DIR" \
          --outer-folds "$OUTER_FOLDS" \
          --inner-folds "$INNER_FOLDS" \
          --repeats "$RUNS" \
          --popsize "$POPSIZE" \
          --max-gen "$MAX_GEN" \
          ${EXTRA_ARGS:-}
      done
    done
  done
done
